title: Kimberly Kayla
logo: ./Kimmy%20-%20Profile%20Pic.jpg
description: I’m a data science enthusiast passionate about turning complex data into actionable insights. From machine learning to data visualization, I love creating innovative solutions. Explore my projects to see how I combine curiosity, creativity, and technical skills to deliver impactful data-driven results. Let’s collaborate on meaningful ventures!
show_downloads: true
theme: jekyll-theme-minimal
