title: Kimberly Kayla
logo: ./Kimmy%20-%20Profile%20Pic.jpg
description: Experienced data professional skilled in transforming data into actionable insights. Proficient in Python, R, SQL, Tableau, and Excel, with expertise in full data workflows. Demonstrated ability in predictive modeling and data-driven strategies to enhance decision-making. Driven to solve challenges and deliver impactful results as a Data Scientist, Analyst, or Engineer.
theme: jekyll-theme-minimal
