title: Kimberly Kayla
logo: Kimmy - Profile Pic
description: I’m a data science enthusiast with a passion for transforming complex data into actionable insights. Whether it’s through machine learning, predictive modeling, or data visualization, I strive to bring innovative solutions to every challenge. Explore my projects, where I combine curiosity, creativity, and technical skills to turn raw data into meaningful outcomes. Let’s connect and collaborate on impactful data-driven ventures!
show_downloads: true
theme: jekyll-theme-minimal
